language: "en"
languages:
  - "en"
  - "de"

show-title: true
title-seconds: 2
spawn-firework: true
# prevent = Prevents people from breaking tier blocks while another user is using them
# close = Closes the other users enchant interface when block is broken
protect-mode: prevent

tiers:
  NETHERITE_BLOCK: 5
  DIAMOND_BLOCK: 4
  GOLD_BLOCK: 3
  IRON_BLOCK: 2